version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "7000:5432"
    environment:
      POSTGRES_USER: nexus
      POSTGRES_PASSWORD: nexus123
      POSTGRES_DB: nexus
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c max_connections=500    
    networks:
      - nexus_network

  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8085:8081"  # Nexus default UI port
      - "5001-5015:5001-5015"  # Optional: Docker registry hosted port
    volumes:
      - nexus_data:/nexus-data
    environment:
      INSTALL4J_ADD_VM_PARAMS: >
        -Xms1200m -Xmx1200m
        -Dnexus.datastore.enabled=true
        -Dnexus.datastore.nexus.jdbcUrl=jdbc:postgresql://postgres:5432/nexus
        -Dnexus.datastore.nexus.username=nexus
        -Dnexus.datastore.nexus.password=nexus123
    networks:
      - nexus_network
    depends_on:
      - postgres

volumes:
  postgres_data:
  nexus_data:

networks:
  nexus_network:
