version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: nexus_postgres
    environment:
      POSTGRES_USER: nexus
      POSTGRES_PASSWORD: nexus123
      POSTGRES_DB: nexus
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c max_connections=500    
    networks:
      - nexus_network

  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8081:8081"
    volumes:
      - nexus_data:/nexus-data
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Dnexus.datastore.enabled=true -Dnexus.datastore.nexus.jdbcUrl=jdbc:postgresql://postgres:5432/nexus -Dnexus.datastore.nexus.username=nexus -Dnexus.datastore.nexus.password=nexus123
    networks:
      - nexus_network
    depends_on:
      - postgres

volumes:
  postgres_data:
  nexus_data:

networks:
  nexus_network: